/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarPreferences: typeof import('./src/components/calendar/CalendarPreferences.vue')['default']
    CalendarSharing: typeof import('./src/components/calendar/CalendarSharing.vue')['default']
    CreateEventModal: typeof import('./src/components/calendar/CreateEventModal.vue')['default']
    DatePickerPopover: typeof import('./src/components/calendar/DatePickerPopover.vue')['default']
    DayModal: typeof import('./src/components/calendar/DayModal.vue')['default']
    DayView: typeof import('./src/components/calendar/DayView.vue')['default']
    EventDetailsModal: typeof import('./src/components/calendar/EventDetailsModal.vue')['default']
    EventFormModal: typeof import('./src/components/calendar/EventFormModal.vue')['default']
    GoogleCalendarSync: typeof import('./src/components/calendar/GoogleCalendarSync.vue')['default']
    ImageUploadModal: typeof import('./src/components/calendar/ImageUploadModal.vue')['default']
    ListView: typeof import('./src/components/calendar/ListView.vue')['default']
    MonthView: typeof import('./src/components/calendar/MonthView.vue')['default']
    RecurringEventEditPromptModal: typeof import('./src/components/calendar/RecurringEventEditPromptModal.vue')['default']
    RecurringEventPromptModal: typeof import('./src/components/calendar/RecurringEventPromptModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/navigation/Sidebar.vue')['default']
    WeatherIcon: typeof import('./src/components/weather/WeatherIcon.vue')['default']
    WeekView: typeof import('./src/components/calendar/WeekView.vue')['default']
  }
}
